### PR TITLE
WIP: Add xarray training notebooks

### LINKED ISSUE #24: Create a "xarray (data access)" Training Notebook
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/dataAccess/` directory that covers accessing local and remote data via `xarray` to assist workshop participants who choose to work on the following projects:
  * [`site/projects/adv_model_vs_obs.md`](https://unidata.github.io/pyaos-ams-2021/projects/adv_model_vs_obs.html)
  * [`site/projects/isentropic_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/isentropic_analysis.html)
  * [`site/projects/model_vs_obs.md`](https://unidata.github.io/pyaos-ams-2021/projects/model_vs_obs.html)
  * [`site/projects/rossby_wave_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/rossby_wave_analysis.html)

Once the notebook is complete, be sure to do the following:

* [ ] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [ ] link the notebook in the following locations using a nbviewer url (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/dataAccess/<training-notebook-name>.ipynb`):
  * [ ] the project page for each project idea listed above
  * [ ] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [ ] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

### LINKED ISSUE #25: Create a "xarray (indexing)" Training Notebook
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/analysis/` directory that covers the basics of indexing in the `xarray` library to assist workshop participants who choose to work on the following projects:
  * [`site/projects/isentropic_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/isentropic_analysis.html)
  * [`site/projects/model_vs_obs.md`](https://unidata.github.io/pyaos-ams-2021/projects/model_vs_obs.html)
  * [`site/projects/rossby_wave_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/rossby_wave_analysis.html)
  * [`site/projects/severe_wx_outbreak.md`](https://unidata.github.io/pyaos-ams-2021/projects/severe_wx_outbreak.html)
  * [`site/projects/severe_wx_outbreak.md`](https://unidata.github.io/pyaos-ams-2021/projects/severe_wx_outbreak.html)

Once the notebook is complete, be sure to do the following:

* [ ] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [ ] link the notebook in the following locations using a nbviewer url (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/analysis/<training-notebook-name>.ipynb`):
  * [ ] the project page for each project idea listed above
  * [ ] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [ ] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

### LINKED ISSUE #26: Create a "xarray (interpolation)" Training Notebook
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/analysis/` directory that covers the ability to perform interpolation using `xarray` to assist workshop participants who choose to work on the following projects:
  * [`site/projects/isentropic_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/isentropic_analysis.html)
  * [`site/projects/model_vs_obs.md`](https://unidata.github.io/pyaos-ams-2021/projects/model_vs_obs.html)
  * [`site/projects/rossby_wave_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/rossby_wave_analysis.html)
  * [`site/projects/severe_wx_outbreak.md`](https://unidata.github.io/pyaos-ams-2021/projects/severe_wx_outbreak.html)

Once the notebook is complete, be sure to do the following:

* [ ] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [ ] link the notebook in the following locations using a nbviewer url (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/analysis/<training-notebook-name>.ipynb`):
  * [ ] the project page for each project idea listed above
  * [ ] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [ ] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

### LINKED ISSUE #27: Create a "xarray (aggregations)" Training Notebook
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/dataAccess/` directory that covers aggregating multiple datasets using `xarray` to assist workshop participants who choose to work on the following projects:
  * [`site/projects/adv_model_vs_obs.md`](https://unidata.github.io/pyaos-ams-2021/projects/adv_model_vs_obs.html)
  * [`site/projects/isentropic_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/isentropic_analysis.html)
  * [`site/projects/rossby_wave_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/rossby_wave_analysis.html)

Once the notebook is complete, be sure to do the following:

* [ ] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [ ] link the notebook in the following locations using a nbviewer url (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/dataAccess/<training-notebook-name>.ipynb`):
  * [ ] the project page for each project idea listed above
  * [ ] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [ ] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

### LINKED ISSUE #28: Create a "xarray (calculations)" Training Notebook
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/analysis/` directory that covers the basics of performing calculations on `xarray` objects to assist workshop participants who choose to work on the following projects:
  * [`site/projects/adv_model_vs_obs.md`](https://unidata.github.io/pyaos-ams-2021/projects/adv_model_vs_obs.html)
  * [`site/projects/isentropic_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/isentropic_analysis.html)
  * [`site/projects/rossby_wave_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/rossby_wave_analysis.html)
  * [`site/projects/severe_wx_outbreak.md`](https://unidata.github.io/pyaos-ams-2021/projects/severe_wx_outbreak.html)

Once the notebook is complete, be sure to do the following:

* [ ] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [ ] link the notebook in the following locations using a nbviewer url (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/analysis/<training-notebook-name>.ipynb`):
  * [ ] the project page for each project idea listed above
  * [ ] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [ ] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

### LINKED ISSUE #33: Create a "MetPy (with xarray)" Training Notebook
Following the [instructors/notebook-template/Template.ipynb](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) template notebook, create a training notebook that lives in `notebooks/analysis/` directory that covers the use of `xarray` in `MetPy` to assist workshop participants who choose to work on the following projects:
  * [`site/projects/isentropic_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/isentropic_analysis.html)
  * [`site/projects/rossby_wave_analysis.md`](https://unidata.github.io/pyaos-ams-2021/projects/rossby_wave_analysis.html)
  * [`site/projects/severe_wx_outbreak.md`](https://unidata.github.io/pyaos-ams-2021/projects/severe_wx_outbreak.html)

Once the notebook is complete, be sure to do the following:

* [ ] clear the output of the notebook
  * jupyter-notebook interface: `Cell` &rarr; `All Output` &rarr; `Clear`
  * jupyter-lab interface: `Right-click` &rarr; `Clear All Outputs`
* [ ] link the notebook in the following locations using a nbviewer url (`https://nbviewer.jupyter.org/github/Unidata/pyaos-ams-2021/blob/master/notebooks/analysis/<training-notebook-name>.ipynb`):
  * [ ] the project page for each project idea listed above
  * [ ] the project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)
* [ ] add a description of the notebook to project entry in [`site/resources.md`](https://unidata.github.io/pyaos-ams-2021/resources.html)

### PR DESCRIPTION
**Pull request by jthielen**
This PR is currently WIP, as I still have the (hopefully easier to complete) xarray-specific notebooks (~~indexing~~, interpolation/regridding, aggregations, and calculations) left to wrap up, but I wanted to put this up in case anyone's up at this hour and wanted to glance through what I have so far.

Below is the list of the issues this PR will close once complete

- [x] Closes #24 
- [x] Closes #25 
- [ ] Closes #26 
- [ ] Closes #27 
- [ ] Closes #28 
- [x] Closes #33

Also note that this cleans up the Rossby Wave project idea as well as providing a sample notebook for guidance (based on prior work I had done), since the project idea was rather vague as it was.

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Awesome!

**Comment by jthielen** [comment]
Unfortunately I've been making slower progress than expected this morning, so I don't quite have all the xarray notebooks complete in time before the initial launch. So sorry about mismanaging that! What I've done is included the completed notebooks I have done, and then "under construction" templates with descriptions for the ones that aren't yet finished (with links to what I plan to reproduce from the xarray docs, so if someone wants to get started right away, they still can). Assuming I can still work during the afternoon today to get those finished up, is this an okay way forward?

**Comment by dcamron** [comment]
> is this an okay way forward?

I think I can pretty comfortably speak for us here when I say that's absolutely okay. If not, I can fight off the others. No problem. Thanks for your work and contributions Jon!

**Comment by lesserwhirls** [comment]
💯 ok path forward as far as I am concerned! We greatly appreciate your herculean efforts here @jthielen!

**Pull request merged**
