### PR TITLE
Add xesmf to environment

### PR DESCRIPTION
**Pull request by jthielen**
While I had hoped to get regridding (with xesmf) and verification metrics (with xskillscore) as a part of the [Advanced Model Output vs. Observations](https://unidata.github.io/pyaos-ams-2021/projects/adv_model_vs_obs.html) project idea, xesmf has a problematic pin of xarray that conflicts with xskillscore, and it doesn't seem like it will be resolved upstream in time. Since regridding is probably the more useful demonstration, let's just go with xesmf.

### CODE REVIEW

**Comment by jthielen** [comment]
Well this is a problem...any ideas on what is going wrong with the windows build? It doesn't look like it's the xarray conflict anymore, but it is still failing due to package conflicts.

**Comment by jthielen** [comment]
Also, in working through the xarray notebooks, I'd like to add cfgrib to the environment as well. Would that be better in this PR or in another?

**Comment by dopplershift** [comment]
*sigh* Booting up the windows VM...

**Comment by dopplershift** [comment]
@jthielen This one's easy, here's your problem:

https://github.com/conda-forge/esmpy-feedstock/blob/b4a3d1898b3dc1aadc92ea53d4d79f20f3c8cd39/recipe/meta.yaml#L23

So apparently more of those *delightful* scientific libraries doesn't work on Windows. (And people wonder why I wanna crack skulls when people crap on Apple for not supporting FORTRAN. How about scientists support Windows before throwing rocks?)

So if this is really important to what you want to do (which is fine), we need to disable windows.

**Comment by jthielen** [comment]
Thanks! Should have guessed it was something like that. I'll close this PR and make a new one disabling windows and adding xesmf, xskillscore, and cfgrib.

**Comment by aaronspring** [comment]
@jthielen anything xskillscore should change with it’s requirements?
Are you aware of this very active xesmf work https://github.com/pangeo-data/xESMF which might work better with uptodate xarray?

**Pull request closed without merging**
